# Generated by Django 3.2 on 2021-05-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_delete_trajet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='stations',
        ),
    ]
