# Generated by Django 3.2 on 2021-05-17 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0003_remove_ligne_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne',
            name='stations',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='metro.station'),
            preserve_default=False,
        ),
    ]
