# Generated by Django 3.2 on 2021-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0005_auto_20210517_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=200)),
                ('arrive', models.CharField(max_length=200)),
                ('stations', models.ManyToManyField(to='metro.Station')),
            ],
        ),
    ]
