# Generated by Django 3.2 on 2021-05-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0006_trajet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='arrive',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='depart',
        ),
    ]
