# Generated by Django 3.2 on 2021-05-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0007_auto_20210518_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='stations',
        ),
        migrations.AddField(
            model_name='trajet',
            name='arrive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='trajet_arrive', to='metro.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trajet',
            name='depart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='trajet_depart', to='metro.station'),
            preserve_default=False,
        ),
    ]
