# Generated by Django 3.2 on 2021-05-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0008_auto_20210518_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trajet',
        ),
    ]
