# Generated by Django 3.2 on 2021-05-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0009_delete_trajet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajet_arrive', to='metro.station')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajet_depart', to='metro.station')),
            ],
        ),
    ]
