# Generated by Django 3.2 on 2021-05-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0010_trajet'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='x_coord',
            field=models.IntegerField(null=True),
        ),
    ]
