# Generated by Django 3.2 on 2021-05-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0012_station_y_coord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='arrive',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='depart',
        ),
        migrations.AddField(
            model_name='trajet',
            name='FromStation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='metro.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trajet',
            name='ToStation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='metro.station'),
            preserve_default=False,
        ),
    ]
