# Generated by Django 3.2 on 2021-05-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0013_auto_20210518_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='x_coord',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='y_coord',
            field=models.FloatField(null=True),
        ),
    ]
