# Generated by Django 3.2 on 2021-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0014_auto_20210518_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='x_coord',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='y_coord',
            field=models.IntegerField(null=True),
        ),
    ]
