# Generated by Django 3.2 on 2021-05-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0015_auto_20210518_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
