# Generated by Django 3.2 on 2021-05-19 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0016_trajet_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
